
package Simulator;

/**
 * 
 * @author Mntsos
 */
public class StartUpFrame extends javax.swing.JFrame {

    /** Creates new form StartUpFrame */
    public StartUpFrame() {
        
        initComponents();
        
         //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartUpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startUpProgressBar = new javax.swing.JProgressBar();
        startUpProgressInfo = new javax.swing.JTextField();
        startUpBackgroundImage = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Εξομοιωτής Festo MPS");
        setBounds(new java.awt.Rectangle(500, 400, 200, 200));
        setForeground(java.awt.Color.white);
        setMinimumSize(new java.awt.Dimension(200, 150));
        setName("StartUpFrame"); // NOI18N
        setResizable(false);

        startUpProgressBar.setForeground(new java.awt.Color(255, 0, 0));
        startUpProgressBar.setMaximum(6);
        startUpProgressBar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        startUpProgressBar.setFocusable(false);

        startUpProgressInfo.setBackground(new java.awt.Color(240, 240, 240));
        startUpProgressInfo.setBorder(null);
        startUpProgressInfo.setFocusable(false);

        startUpBackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Simulator.png"))); // NOI18N
        startUpBackgroundImage.setMaximumSize(new java.awt.Dimension(400, 150));
        startUpBackgroundImage.setMinimumSize(new java.awt.Dimension(400, 150));
        startUpBackgroundImage.setName(""); // NOI18N
        startUpBackgroundImage.setPreferredSize(new java.awt.Dimension(400, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(startUpProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(startUpBackgroundImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(startUpProgressInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(startUpBackgroundImage, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startUpProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startUpProgressInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel startUpBackgroundImage;
    private javax.swing.JProgressBar startUpProgressBar;
    private javax.swing.JTextField startUpProgressInfo;
    // End of variables declaration//GEN-END:variables

    /**
     * 
     * @param str
     */
    public void updateProgressInfo( String str ) {
        
        startUpProgressInfo.setText( str );
    }
    
    /**
     * 
     * @param n
     */
    public void updateProgresBar( int n ) {
        
        startUpProgressBar.setValue( n );
    }

}
