
package Simulator;

import FestoMPS3D.*;
import java.awt.*;

public class MainFrame extends javax.swing.JFrame {
    
    protected int workpiecesValue = -1;

    /** Creates new form MainForm */
    public MainFrame() {
        initComponents();
        
                /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
  
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        aboutF = new javax.swing.JDialog();
        executionP = new javax.swing.JPanel();
        wSCtrlP = new javax.swing.JPanel();
        startStop_wS = new javax.swing.JButton();
        startStopLed_wS = new javax.swing.JRadioButton();
        removeRejectedWorkpiece_wS = new javax.swing.JButton();
        removeColoredWorkpiece_wS = new javax.swing.JButton();
        removeBlackWorkpiece_wS = new javax.swing.JButton();
        pSCtrlP = new javax.swing.JPanel();
        startStop_pS = new javax.swing.JButton();
        startStopLed_pS = new javax.swing.JRadioButton();
        tSCtrlP = new javax.swing.JPanel();
        startStop_tS = new javax.swing.JButton();
        startStopLed_tS = new javax.swing.JRadioButton();
        removeRejectedWorkpiece_tS = new javax.swing.JButton();
        dSCtrlP = new javax.swing.JPanel();
        startStop_dS = new javax.swing.JButton();
        startStopLed_dS = new javax.swing.JRadioButton();
        addRejectedWorkpiece_dS = new javax.swing.JButton();
        addAcceptedWorkpiece_dS = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dSInfo = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tSInfo = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        pSInfo = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        wSInfo = new javax.swing.JTextArea();
        propertiesP = new javax.swing.JPanel();
        systemCtrlP = new javax.swing.JPanel();
        Reset = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        topBar = new javax.swing.JMenuBar();
        topMenuFile = new javax.swing.JMenu();
        topMenuFileClose = new javax.swing.JMenuItem();
        topMenuEdit = new javax.swing.JMenu();
        topMenuHelp = new javax.swing.JMenu();
        topMenuHelpHelp = new javax.swing.JMenuItem();
        topMenuHelpAbout = new javax.swing.JMenuItem();

        aboutF.setTitle("aboutF");
        aboutF.setAlwaysOnTop(true);
        aboutF.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        aboutF.setFocusable(false);
        aboutF.setLocationByPlatform(true);
        aboutF.setMinimumSize(new java.awt.Dimension(50, 50));
        aboutF.setName("aboutF"); // NOI18N

        javax.swing.GroupLayout aboutFLayout = new javax.swing.GroupLayout(aboutF.getContentPane());
        aboutF.getContentPane().setLayout(aboutFLayout);
        aboutFLayout.setHorizontalGroup(
            aboutFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        aboutFLayout.setVerticalGroup(
            aboutFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Festo MPS Simulator");
        setBounds(new java.awt.Rectangle(100, 200, 1000, 700));
        setMinimumSize(new java.awt.Dimension(1057, 740));
        setName("MainFrame"); // NOI18N

        executionP.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        executionP.setMinimumSize(new java.awt.Dimension(800, 400));
        executionP.setName("executionP"); // NOI18N
        executionP.setPreferredSize(new java.awt.Dimension(800, 400));
        executionP.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                executionPAncestorResized(evt);
            }
        });

        javax.swing.GroupLayout executionPLayout = new javax.swing.GroupLayout(executionP);
        executionP.setLayout(executionPLayout);
        executionPLayout.setHorizontalGroup(
            executionPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 827, Short.MAX_VALUE)
        );
        executionPLayout.setVerticalGroup(
            executionPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );

        wSCtrlP.setBorder(javax.swing.BorderFactory.createTitledBorder("Warehousing Station's Controls"));
        wSCtrlP.setMinimumSize(new java.awt.Dimension(200, 150));
        wSCtrlP.setPreferredSize(new java.awt.Dimension(200, 150));

        startStop_wS.setFont(new java.awt.Font("Tahoma", 0, 10));
        startStop_wS.setText("Start");
        startStop_wS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startStop_wSMouseClicked(evt);
            }
        });

        startStopLed_wS.setBackground(new java.awt.Color(255, 0, 0));
        startStopLed_wS.setBorderPainted(true);
        startStopLed_wS.setEnabled(false);
        startStopLed_wS.setFocusable(false);

        removeRejectedWorkpiece_wS.setFont(new java.awt.Font("Tahoma", 0, 10));
        removeRejectedWorkpiece_wS.setText("Remove rejected workpiece");
        removeRejectedWorkpiece_wS.setToolTipText("");
        removeRejectedWorkpiece_wS.setActionCommand("removeRejectedWorkpiece_wS");
        removeRejectedWorkpiece_wS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeRejectedWorkpiece_wSMouseClicked(evt);
            }
        });

        removeColoredWorkpiece_wS.setFont(new java.awt.Font("Tahoma", 0, 10));
        removeColoredWorkpiece_wS.setText("Remove colored workpiece");
        removeColoredWorkpiece_wS.setActionCommand("removeNonBlackWorkpiece_wS");
        removeColoredWorkpiece_wS.setMaximumSize(new java.awt.Dimension(157, 21));
        removeColoredWorkpiece_wS.setMinimumSize(new java.awt.Dimension(157, 21));
        removeColoredWorkpiece_wS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeColoredWorkpiece_wSMouseClicked(evt);
            }
        });

        removeBlackWorkpiece_wS.setFont(new java.awt.Font("Tahoma", 0, 10));
        removeBlackWorkpiece_wS.setText("Remove black workpiece");
        removeBlackWorkpiece_wS.setToolTipText("");
        removeBlackWorkpiece_wS.setActionCommand("removeBlackWorkpiece_wS");
        removeBlackWorkpiece_wS.setMaximumSize(new java.awt.Dimension(157, 23));
        removeBlackWorkpiece_wS.setMinimumSize(new java.awt.Dimension(157, 23));
        removeBlackWorkpiece_wS.setPreferredSize(new java.awt.Dimension(145, 23));
        removeBlackWorkpiece_wS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeBlackWorkpiece_wSMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout wSCtrlPLayout = new javax.swing.GroupLayout(wSCtrlP);
        wSCtrlP.setLayout(wSCtrlPLayout);
        wSCtrlPLayout.setHorizontalGroup(
            wSCtrlPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wSCtrlPLayout.createSequentialGroup()
                .addGroup(wSCtrlPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(wSCtrlPLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(startStop_wS)
                        .addGap(18, 18, 18)
                        .addComponent(startStopLed_wS))
                    .addGroup(wSCtrlPLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(wSCtrlPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(removeBlackWorkpiece_wS, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(removeRejectedWorkpiece_wS, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                            .addComponent(removeColoredWorkpiece_wS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))))
                .addContainerGap())
        );
        wSCtrlPLayout.setVerticalGroup(
            wSCtrlPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wSCtrlPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(wSCtrlPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(startStopLed_wS)
                    .addComponent(startStop_wS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeBlackWorkpiece_wS, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeColoredWorkpiece_wS, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeRejectedWorkpiece_wS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33))
        );

        pSCtrlP.setBorder(javax.swing.BorderFactory.createTitledBorder("Processing Station's Controls"));
        pSCtrlP.setMinimumSize(new java.awt.Dimension(200, 150));
        pSCtrlP.setPreferredSize(new java.awt.Dimension(200, 150));

        startStop_pS.setFont(new java.awt.Font("Tahoma", 0, 10));
        startStop_pS.setText("Start");
        startStop_pS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startStop_pSMouseClicked(evt);
            }
        });

        startStopLed_pS.setBackground(new java.awt.Color(255, 0, 51));
        startStopLed_pS.setEnabled(false);
        startStopLed_pS.setFocusable(false);

        javax.swing.GroupLayout pSCtrlPLayout = new javax.swing.GroupLayout(pSCtrlP);
        pSCtrlP.setLayout(pSCtrlPLayout);
        pSCtrlPLayout.setHorizontalGroup(
            pSCtrlPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSCtrlPLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(startStop_pS)
                .addGap(18, 18, 18)
                .addComponent(startStopLed_pS)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        pSCtrlPLayout.setVerticalGroup(
            pSCtrlPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSCtrlPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pSCtrlPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(startStopLed_pS)
                    .addComponent(startStop_pS))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        tSCtrlP.setBorder(javax.swing.BorderFactory.createTitledBorder("Testing Station's Controls"));
        tSCtrlP.setMinimumSize(new java.awt.Dimension(200, 150));
        tSCtrlP.setPreferredSize(new java.awt.Dimension(200, 150));

        startStop_tS.setFont(new java.awt.Font("Tahoma", 0, 10));
        startStop_tS.setText("Start");
        startStop_tS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startStop_tSMouseClicked(evt);
            }
        });

        startStopLed_tS.setBackground(new java.awt.Color(255, 0, 0));
        startStopLed_tS.setEnabled(false);
        startStopLed_tS.setFocusable(false);

        removeRejectedWorkpiece_tS.setFont(new java.awt.Font("Tahoma", 0, 10));
        removeRejectedWorkpiece_tS.setText("Remove rejected workpiece");
        removeRejectedWorkpiece_tS.setPreferredSize(new java.awt.Dimension(145, 21));
        removeRejectedWorkpiece_tS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeRejectedWorkpiece_tSMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tSCtrlPLayout = new javax.swing.GroupLayout(tSCtrlP);
        tSCtrlP.setLayout(tSCtrlPLayout);
        tSCtrlPLayout.setHorizontalGroup(
            tSCtrlPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tSCtrlPLayout.createSequentialGroup()
                .addGroup(tSCtrlPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tSCtrlPLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(startStop_tS)
                        .addGap(18, 18, 18)
                        .addComponent(startStopLed_tS))
                    .addGroup(tSCtrlPLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(removeRejectedWorkpiece_tS, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tSCtrlPLayout.setVerticalGroup(
            tSCtrlPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tSCtrlPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tSCtrlPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(startStopLed_tS)
                    .addComponent(startStop_tS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeRejectedWorkpiece_tS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        dSCtrlP.setBorder(javax.swing.BorderFactory.createTitledBorder("Distribution Station's Controls"));
        dSCtrlP.setMinimumSize(new java.awt.Dimension(200, 150));
        dSCtrlP.setPreferredSize(new java.awt.Dimension(200, 150));

        startStop_dS.setFont(new java.awt.Font("Tahoma", 0, 10));
        startStop_dS.setText("Start");
        startStop_dS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startStop_dSMouseClicked(evt);
            }
        });

        startStopLed_dS.setBackground(new java.awt.Color(255, 0, 51));
        startStopLed_dS.setEnabled(false);
        startStopLed_dS.setFocusable(false);

        addRejectedWorkpiece_dS.setFont(new java.awt.Font("Tahoma", 0, 10));
        addRejectedWorkpiece_dS.setText("Add rejected workpiece");
        addRejectedWorkpiece_dS.setActionCommand("addRejectedWorkpiece_dS");
        addRejectedWorkpiece_dS.setMaximumSize(new java.awt.Dimension(157, 21));
        addRejectedWorkpiece_dS.setMinimumSize(new java.awt.Dimension(157, 21));
        addRejectedWorkpiece_dS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addRejectedWorkpiece_dSMouseClicked(evt);
            }
        });

        addAcceptedWorkpiece_dS.setFont(new java.awt.Font("Tahoma", 0, 10));
        addAcceptedWorkpiece_dS.setText("Add accepted workpiece");
        addAcceptedWorkpiece_dS.setActionCommand("addAcceptedWorkpiece_dS");
        addAcceptedWorkpiece_dS.setMaximumSize(new java.awt.Dimension(157, 21));
        addAcceptedWorkpiece_dS.setMinimumSize(new java.awt.Dimension(157, 21));
        addAcceptedWorkpiece_dS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addAcceptedWorkpiece_dSMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout dSCtrlPLayout = new javax.swing.GroupLayout(dSCtrlP);
        dSCtrlP.setLayout(dSCtrlPLayout);
        dSCtrlPLayout.setHorizontalGroup(
            dSCtrlPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dSCtrlPLayout.createSequentialGroup()
                .addGroup(dSCtrlPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dSCtrlPLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(startStop_dS)
                        .addGap(18, 18, 18)
                        .addComponent(startStopLed_dS))
                    .addGroup(dSCtrlPLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addAcceptedWorkpiece_dS, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                    .addGroup(dSCtrlPLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addRejectedWorkpiece_dS, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)))
                .addContainerGap())
        );
        dSCtrlPLayout.setVerticalGroup(
            dSCtrlPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dSCtrlPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dSCtrlPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(startStopLed_dS)
                    .addComponent(startStop_dS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addAcceptedWorkpiece_dS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addRejectedWorkpiece_dS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(64, 64, 64))
        );

        dSInfo.setColumns(20);
        dSInfo.setEditable(false);
        dSInfo.setFont(new java.awt.Font("Monospaced", 0, 10));
        dSInfo.setLineWrap(true);
        dSInfo.setRows(10);
        dSInfo.setWrapStyleWord(true);
        dSInfo.setMinimumSize(new java.awt.Dimension(200, 150));
        dSInfo.setPreferredSize(new java.awt.Dimension(200, 150));
        jScrollPane1.setViewportView(dSInfo);

        tSInfo.setColumns(20);
        tSInfo.setEditable(false);
        tSInfo.setFont(new java.awt.Font("Monospaced", 0, 10));
        tSInfo.setLineWrap(true);
        tSInfo.setRows(10);
        tSInfo.setMinimumSize(new java.awt.Dimension(200, 150));
        tSInfo.setPreferredSize(new java.awt.Dimension(200, 150));
        jScrollPane2.setViewportView(tSInfo);

        pSInfo.setColumns(20);
        pSInfo.setEditable(false);
        pSInfo.setFont(new java.awt.Font("Monospaced", 0, 10));
        pSInfo.setLineWrap(true);
        pSInfo.setRows(10);
        pSInfo.setMinimumSize(new java.awt.Dimension(200, 150));
        pSInfo.setPreferredSize(new java.awt.Dimension(200, 150));
        jScrollPane3.setViewportView(pSInfo);

        wSInfo.setColumns(20);
        wSInfo.setEditable(false);
        wSInfo.setFont(new java.awt.Font("Monospaced", 0, 10));
        wSInfo.setLineWrap(true);
        wSInfo.setRows(10);
        wSInfo.setMinimumSize(new java.awt.Dimension(200, 150));
        wSInfo.setPreferredSize(new java.awt.Dimension(200, 150));
        jScrollPane4.setViewportView(wSInfo);

        propertiesP.setBorder(javax.swing.BorderFactory.createTitledBorder("Properties"));
        propertiesP.setMinimumSize(new java.awt.Dimension(178, 400));

        javax.swing.GroupLayout propertiesPLayout = new javax.swing.GroupLayout(propertiesP);
        propertiesP.setLayout(propertiesPLayout);
        propertiesPLayout.setHorizontalGroup(
            propertiesPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );
        propertiesPLayout.setVerticalGroup(
            propertiesPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );

        systemCtrlP.setBorder(javax.swing.BorderFactory.createTitledBorder("System's Controls"));
        systemCtrlP.setMinimumSize(new java.awt.Dimension(200, 150));
        systemCtrlP.setPreferredSize(new java.awt.Dimension(200, 150));

        Reset.setFont(new java.awt.Font("Tahoma", 0, 10));
        Reset.setLabel("Reset");

        jButton1.setText("jButton1");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout systemCtrlPLayout = new javax.swing.GroupLayout(systemCtrlP);
        systemCtrlP.setLayout(systemCtrlPLayout);
        systemCtrlPLayout.setHorizontalGroup(
            systemCtrlPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(systemCtrlPLayout.createSequentialGroup()
                .addGroup(systemCtrlPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Reset)
                    .addComponent(jButton1))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        systemCtrlPLayout.setVerticalGroup(
            systemCtrlPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(systemCtrlPLayout.createSequentialGroup()
                .addComponent(Reset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        Reset.getAccessibleContext().setAccessibleDescription("");

        topMenuFile.setText("File");
        topMenuFile.setName("File"); // NOI18N

        topMenuFileClose.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        topMenuFileClose.setText("Close");
        topMenuFileClose.setName("Close"); // NOI18N
        topMenuFileClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                topMenuFileCloseMouseClicked(evt);
            }
        });
        topMenuFile.add(topMenuFileClose);
        topMenuFileClose.getAccessibleContext().setAccessibleDescription("");

        topBar.add(topMenuFile);

        topMenuEdit.setText("Edit");
        topBar.add(topMenuEdit);

        topMenuHelp.setText("Help");

        topMenuHelpHelp.setText("Help");
        topMenuHelp.add(topMenuHelpHelp);

        topMenuHelpAbout.setText("About");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, aboutF, org.jdesktop.beansbinding.ELProperty.create("${autoRequestFocus}true"), topMenuHelpAbout, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        topMenuHelpAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                topMenuHelpAboutMouseReleased(evt);
            }
        });
        topMenuHelpAbout.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
                topMenuHelpAboutMenuKeyReleased(evt);
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        topMenuHelp.add(topMenuHelpAbout);

        topBar.add(topMenuHelp);

        setJMenuBar(topBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(systemCtrlP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(propertiesP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(dSCtrlP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(tSCtrlP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pSCtrlP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(wSCtrlP, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                                .addGap(6, 6, 6))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)))
                    .addComponent(executionP, javax.swing.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(executionP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(propertiesP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tSCtrlP, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addComponent(dSCtrlP, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addComponent(wSCtrlP, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addComponent(pSCtrlP, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addComponent(systemCtrlP, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                .addContainerGap())
        );

        executionP.getAccessibleContext().setAccessibleName("");

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void topMenuFileCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topMenuFileCloseMouseClicked
        System.exit( 0 );
    }//GEN-LAST:event_topMenuFileCloseMouseClicked

    private void topMenuHelpAboutMenuKeyReleased(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_topMenuHelpAboutMenuKeyReleased
        aboutF.setVisible( true );
    }//GEN-LAST:event_topMenuHelpAboutMenuKeyReleased

    private void topMenuHelpAboutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topMenuHelpAboutMouseReleased
        aboutF.setVisible( true );
    }//GEN-LAST:event_topMenuHelpAboutMouseReleased

    private void executionPAncestorResized(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_executionPAncestorResized
        FestoMPS.resizeCanvas( this );
    }//GEN-LAST:event_executionPAncestorResized

    private void startStop_wSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startStop_wSMouseClicked

        GuiBinder.propagateEvent( "wS", startStop_wS.getText() );
    }//GEN-LAST:event_startStop_wSMouseClicked

    private void startStop_pSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startStop_pSMouseClicked
        
        GuiBinder.propagateEvent( "pS", startStop_pS.getText() );
    }//GEN-LAST:event_startStop_pSMouseClicked

    private void startStop_tSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startStop_tSMouseClicked
        GuiBinder.propagateEvent( "tS", startStop_tS.getText() );
    }//GEN-LAST:event_startStop_tSMouseClicked

    private void startStop_dSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startStop_dSMouseClicked
        
        GuiBinder.propagateEvent( "dS", startStop_dS.getText() );
    }//GEN-LAST:event_startStop_dSMouseClicked

    private void addRejectedWorkpiece_dSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addRejectedWorkpiece_dSMouseClicked
        GuiBinder.propagateEvent( "dS", addRejectedWorkpiece_dS.getText() );
    }//GEN-LAST:event_addRejectedWorkpiece_dSMouseClicked

    private void addAcceptedWorkpiece_dSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addAcceptedWorkpiece_dSMouseClicked
        GuiBinder.propagateEvent( "dS", addAcceptedWorkpiece_dS.getText() );
    }//GEN-LAST:event_addAcceptedWorkpiece_dSMouseClicked

    private void removeBlackWorkpiece_wSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeBlackWorkpiece_wSMouseClicked
        GuiBinder.propagateEvent( "wS", removeBlackWorkpiece_wS.getText() );
    }//GEN-LAST:event_removeBlackWorkpiece_wSMouseClicked

    private void removeColoredWorkpiece_wSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeColoredWorkpiece_wSMouseClicked
        GuiBinder.propagateEvent( "wS", removeColoredWorkpiece_wS.getText() );
    }//GEN-LAST:event_removeColoredWorkpiece_wSMouseClicked

    private void removeRejectedWorkpiece_wSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeRejectedWorkpiece_wSMouseClicked
        GuiBinder.propagateEvent( "wS", removeRejectedWorkpiece_wS.getText() );
    }//GEN-LAST:event_removeRejectedWorkpiece_wSMouseClicked

    private void removeRejectedWorkpiece_tSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeRejectedWorkpiece_tSMouseClicked
        GuiBinder.propagateEvent( "tS", removeRejectedWorkpiece_tS.getText() );
    }//GEN-LAST:event_removeRejectedWorkpiece_tSMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        FestoMPS.system3D.getCanvas3D().paintAll( FestoMPS.system3D.getCanvas3D().getGraphics() );
        GuiBinder.propagateEvent( "dS", "a" );
        FestoMPS.system3D.getCanvas3D().paintAll( FestoMPS.system3D.getCanvas3D().getGraphics() );
    }//GEN-LAST:event_jButton1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Reset;
    private javax.swing.JDialog aboutF;
    private javax.swing.JButton addAcceptedWorkpiece_dS;
    private javax.swing.JButton addRejectedWorkpiece_dS;
    private javax.swing.JPanel dSCtrlP;
    private javax.swing.JTextArea dSInfo;
    private javax.swing.JPanel executionP;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel pSCtrlP;
    private javax.swing.JTextArea pSInfo;
    private javax.swing.JPanel propertiesP;
    private javax.swing.JButton removeBlackWorkpiece_wS;
    private javax.swing.JButton removeColoredWorkpiece_wS;
    private javax.swing.JButton removeRejectedWorkpiece_tS;
    private javax.swing.JButton removeRejectedWorkpiece_wS;
    private javax.swing.JRadioButton startStopLed_dS;
    private javax.swing.JRadioButton startStopLed_pS;
    private javax.swing.JRadioButton startStopLed_tS;
    private javax.swing.JRadioButton startStopLed_wS;
    private javax.swing.JButton startStop_dS;
    private javax.swing.JButton startStop_pS;
    private javax.swing.JButton startStop_tS;
    private javax.swing.JButton startStop_wS;
    private javax.swing.JPanel systemCtrlP;
    private javax.swing.JPanel tSCtrlP;
    private javax.swing.JTextArea tSInfo;
    private javax.swing.JMenuBar topBar;
    private javax.swing.JMenu topMenuEdit;
    private javax.swing.JMenu topMenuFile;
    private javax.swing.JMenuItem topMenuFileClose;
    private javax.swing.JMenu topMenuHelp;
    private javax.swing.JMenuItem topMenuHelpAbout;
    private javax.swing.JMenuItem topMenuHelpHelp;
    private javax.swing.JPanel wSCtrlP;
    private javax.swing.JTextArea wSInfo;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    
    /*
     * Στο σημείο αυτό τοποθετούνται οι custom συναρτήσεις που χρησιμοποιούμε
     */
    public int getExecutionWidth() {
        
        return executionP.getWidth();
    }
    
    public int getExecutionHeight() {
        
        return executionP.getHeight();
    }
    
    public javax.swing.JPanel getExecutionP() {
        
        return executionP;
    }
    
    public com.sun.j3d.exp.swing.JCanvas3D getJCanvas3D() {
        return ( com.sun.j3d.exp.swing.JCanvas3D ) executionP;
    }
    
    public void addExecutionP( java.awt.Canvas comp ) {
            
        executionP.add( comp, java.awt.BorderLayout.CENTER );
    }
    
    public void updateStatus( String station, String status ) {
        
        switch( station ) {
            case "dS":
                dSInfo.append( status );
                break;
            case "tS":
                tSInfo.append( status );
                break;
            case "pS":
                pSInfo.append( status );
                break;
            case "wS":
                wSInfo.append( status );
                break;
            default:
                break;
        }
    }
    
    public void updateControls( String station, String control, String cmd ) {
        
        javax.swing.JButton startStop = null;
        javax.swing.JRadioButton mainLed = null;
        
        switch( station ) {
            case "dS":
                startStop = startStop_dS;
                mainLed = startStopLed_dS;
                break;
            case "tS":
                startStop = startStop_tS;
                mainLed = startStopLed_tS;
                break;
            case "pS":
                startStop = startStop_pS;
                mainLed = startStopLed_pS;
                break;
            case "wS":
                startStop = startStop_wS;
                mainLed = startStopLed_wS;
                break;
            default:
                return;
        }
        
        switch( control ) {
            case "mainButton": 
                if( cmd.matches( "Stop" ) )
                    startStop.setText( "Stop" );
                else
                    startStop.setText( "Start" );
                break;
            case "mainLed":
                if( cmd.matches( "Off" ) )
                    mainLed.setBackground( Color.RED );
                else if ( cmd.matches( "Initializing" ) )
                    mainLed.setBackground( Color.ORANGE );
                else if ( cmd.matches( "On" ) )
                    mainLed.setBackground( Color.GREEN );
                break;
            default:
                break;
        }
    }   

}
